name: publish-package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      # Note, this is set up following this tutorial:
      # https://packaging.python.org/en/latest/tutorials/packaging-projects/
      # This relies on the pyproject.toml file.
      - name: Build and publish
        run: |
          python -m build
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_ACCESS_TOKEN }} dist/*